name: GitHub Activity Graph

on:
  schedule:
    - cron: "0 0 * * *"   # обновляется каждый день
  workflow_dispatch:       # можно запустить вручную

jobs:
  update-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Generate GitHub Activity Graph
        uses: Ashutosh00710/github-readme-activity-graph@main
        with:
          username: AlmazIsDev
          theme: react-dark
          bg_color: 20232a
          hide_border: true
          area: true
          custom_title: Contribution%20Graph%20(last%2031%20days)
          output: ./assets/activity-graph.svg   # сохраняем в папку assets

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/activity-graph.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Update activity graph"
          git push
